global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "Prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  
  - job_name: "RabbitMQ"
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "Grafana"
    static_configs:
      - targets: ["grafana:3000"]