{
 "title": "prometheus-net",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instances",
    "label": "instances",
    "query": "label_values(http_requests_received_total, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Start time of the process",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"Prometheus-Net\"} * 1000"
    }
   ]
  },
  { "title": "Product", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Message processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 7 },
   "targets": [
    { "expr": "product_message_time_sum{}", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Add product processing time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 7 },
   "targets": [
    { "expr": "product_addproduct_time_sum{}", "legendFormat": "{{le}}" }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "myapp_document_imports_in_progress{}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of product operations done",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 16 },
   "targets": [
    { "expr": "myapp_jobs_processed_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "HTTP ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "All http request duration second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "interval" },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total[$interval])",
     "legendFormat": "Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_handles", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes /1024/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "process cpu seconds total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"localhost:1234\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "dotnet total memory in MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}